[build]
publish = "www"

[context.production]
command = "git submodule update --init --remote && npm run build"

  [context.production.environment]
  ELEVENTY_ENV = "production"
  NODE_ENV = "production"
  NODE_VERSION = "16"
  TZ = "Europe/London"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]

[[plugins]]
package = "netlify-plugin-webmentions"

[[headers]]
for = "/*"

  [headers.values]
  Content-Security-Policy = "script-src 'self' 'nonce-bVgyaDV6YU9tdThnZ2wwckZBNnFnc1Z6Wk40SnY2U0pmbjdTUjQ3MVg2RTFCbnEwN3g='; style-src 'self' 'unsafe-inline'; object-src 'self'; img-src 'self' data: *.apple.com shots.codepen.io gravatar.com *.media-amazon.com img.youtube.com i.vimeocdn.com"
  Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1; mode=block"

[[headers]]
for = "/*.ico"

  [headers.values]
  Content-Type = "image/x-icon"

[[headers]]
for = "/*.js"

  [headers.values]
  Content-Type = "text/javascript; charset=utf-8"

[[headers]]
for = "/*.json"

  [headers.values]
  Content-Type = "application/json; charset=utf-8"

[[headers]]
for = "/*.webmanifest"

  [headers.values]
  Content-Type = "application/manifest+json; charset=utf-8"

[[headers]]
for = "/.well-known/webfinger"

  [headers.values]
  Content-Type = "application/jrd+json; charset=UTF-8"

[[redirects]]
from = "/images/og/*"
to = "/.netlify/images?url=/media/:splat&w=1200&h=630&fit=cover"
status = 200

[[redirects]]
from = "/images/:width/*"
to = "/.netlify/images?url=/media/:splat&w=:width"
status = 200

[[redirects]]
from = "/categories/:tag/"
to = "/categories/:tag/page/:p.html"
status = 200
force = true

  [redirects.query]
  page = ":p"

[[redirects]]
from = "/articles/"
to = "/articles/page/:p.html"
status = 200
force = true

  [redirects.query]
  page = ":p"

[[redirects]]
from = "/bookmarks/"
to = "/bookmarks/page/:p.html"
status = 200
force = true

  [redirects.query]
  page = ":p"

[[redirects]]
from = "/events/"
to = "/events/page/:p.html"
status = 200
force = true

  [redirects.query]
  page = ":p"

[[redirects]]
from = "/jams/"
to = "/jams/page/:p.html"
status = 200
force = true

  [redirects.query]
  page = ":p"

[[redirects]]
from = "/notes/"
to = "/notes/page/:p.html"
status = 200
force = true

  [redirects.query]
  page = ":p"

[[redirects]]
from = "/photos/"
to = "/photos/page/:p.html"
status = 200
force = true

  [redirects.query]
  page = ":p"

[[redirects]]
from = "/replies/"
to = "/replies/page/:p.html"
status = 200
force = true

  [redirects.query]
  page = ":p"
